name: fruait
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  camera: ^0.11.0+1
  card_actions: ^0.0.1
  cloud_firestore: ^5.3.0
  connectivity: ^3.0.6
  external_path: ^1.0.3
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  gap: ^3.0.1
  get: ^4.6.6
  image: ^4.2.0
  image_picker: ^1.1.2
  media_scanner: ^2.1.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  tflite_flutter: ^0.10.4
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/center.png
    - assets/logo.png
    - assets/background.png
    - assets/google.png
    - assets/model/model.tflite
    - assets/model/banana.tflite
    - assets/model/guava.tflite
    - assets/model/orange.tflite
    - assets/model/mango.tflite
    - assets/model/tomato.tflite
    - assets/